import { globSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { unwrapProse } from './prose.js';

/*
 * #776's fourth and sixth ACs as a gate, in the mold of `adrNumbers.usage.
 * spec.ts` and `spelling.usage.spec.ts`: `unwrapProse` (`./prose.ts`)
 * unwraps hard-wrapped markdown prose back to one line per paragraph,
 * list item and blockquote, without touching a fenced code block, a
 * table, a heading, front matter, a link reference definition, or a
 * deliberate hard break. Applied to a file already on trunk it is a
 * no-op once that file has no hard-wrapped prose left, so the second
 * `describe` below asserts that no-op across every in-scope file -- a PR
 * that reintroduces a wrapped paragraph makes `unwrapProse` change the
 * file again and fails the same check the #776 migration itself ran. See
 * `prose.ts`'s own comment for why the logic lives in its own module
 * rather than inline here the way those two specs do theirs.
 *
 * Out of scope, same as `spelling.usage.spec.ts`'s exclusions and for the
 * same reason: `docs/research/transcripts/`, verbatim auto-generated
 * captions with no author to have wrapped them on purpose, and
 * `docs/design/doula-cloud.export.md`, generated by `bun run
 * design:export` from `scripts/design-export.ts`'s own template -- fixed
 * there (see that script's `renderExport`), not by rewriting its output.
 */

describe('unwrapProse', () => {
	it('joins a paragraph wrapped across two lines', () => {
		expect(unwrapProse('Line one continues onto\na second line here.')).toBe(
			'Line one continues onto a second line here.'
		);
	});

	it('keeps two blank-line-separated paragraphs separate, each joined on its own', () => {
		expect(
			unwrapProse(
				'First para line one\nfirst para line two.\n\nSecond para line one\nsecond para line two.'
			)
		).toBe('First para line one first para line two.\n\nSecond para line one second para line two.');
	});

	it('leaves a heading alone and does not join it with the paragraph after it', () => {
		expect(unwrapProse('# Heading text\n\nBody line one\nbody line two.')).toBe(
			'# Heading text\n\nBody line one body line two.'
		);
	});

	it('lets a heading interrupt a paragraph with no blank line between them', () => {
		expect(unwrapProse('# Heading\nParagraph text right after.')).toBe(
			'# Heading\nParagraph text right after.'
		);
	});

	it('leaves a thematic break alone between two joined paragraphs', () => {
		expect(unwrapProse('Para before.\n\n---\n\nPara after continues\nonto next line.')).toBe(
			'Para before.\n\n---\n\nPara after continues onto next line.'
		);
	});

	it('lets a thematic break interrupt a paragraph with no blank line between them', () => {
		const document_ = 'Paragraph line one continues\n***\nAnother paragraph after the break.';
		expect(unwrapProse(document_)).toBe(document_);
	});

	it('never touches a fenced code block, even one holding a heading- or list-shaped line', () => {
		const document_ =
			'Before text.\n\n```\n# Not a heading\n- not a list\n```\n\nAfter text continues\nonto next line.';
		expect(unwrapProse(document_)).toBe(
			'Before text.\n\n```\n# Not a heading\n- not a list\n```\n\nAfter text continues onto next line.'
		);
	});

	it('copies an unclosed fence through verbatim to the end of the file', () => {
		const document_ = 'Intro line.\n\n```\nunclosed content\nmore content';
		expect(unwrapProse(document_)).toBe(document_);
	});

	it('does not let a mismatched fence character close the block', () => {
		const document_ = '```\nline a\n~~~\nline b\n```';
		expect(unwrapProse(document_)).toBe(document_);
	});

	it('does not let a shorter run of the same fence character close the block', () => {
		const document_ = '````\ncode\n```\nmore code\n````';
		expect(unwrapProse(document_)).toBe(document_);
	});

	it('leaves a link reference definition alone and does not join it into a paragraph', () => {
		expect(unwrapProse('[ref]: https://example.com/foo\n\nPara line one\npara line two.')).toBe(
			'[ref]: https://example.com/foo\n\nPara line one para line two.'
		);
	});

	it('lets a link reference definition interrupt a paragraph with no blank line between them', () => {
		const document_ = 'Paragraph text here\n[ref2]: https://example.com/bar\nMore paragraph text.';
		expect(unwrapProse(document_)).toBe(document_);
	});

	it('never touches a table, and stops the table at the first blank line', () => {
		const document_ =
			'Intro.\n\n| A | B |\n| --- | --- |\n| 1 | 2 |\n| 3 | 4 |\n\nOutro continues\nonto next line.';
		expect(unwrapProse(document_)).toBe(
			'Intro.\n\n| A | B |\n| --- | --- |\n| 1 | 2 |\n| 3 | 4 |\n\nOutro continues onto next line.'
		);
	});

	it('lets a table interrupt a paragraph with no blank line between them', () => {
		const document_ = 'Some paragraph text\n| A | B |\n| --- | --- |\n| 1 | 2 |';
		expect(unwrapProse(document_)).toBe(document_);
	});

	it('does not mistake a lone pipe on the last line of the file for a table', () => {
		const document_ = 'Last line with a | pipe in it';
		expect(unwrapProse(document_)).toBe(document_);
	});

	it('joins a blockquote paragraph wrapped across two lines, keeping the marker', () => {
		expect(unwrapProse('> Quoted line one\n> quoted line two continues.')).toBe(
			'> Quoted line one quoted line two continues.'
		);
	});

	it('keeps two paragraphs inside one blockquote separate, each joined on its own', () => {
		const document_ =
			'> First quoted paragraph\n> continues here.\n>\n> Second quoted paragraph\n> continues too.';
		expect(unwrapProse(document_)).toBe(
			'> First quoted paragraph continues here.\n>\n> Second quoted paragraph continues too.'
		);
	});

	it('joins a nested blockquote paragraph, keeping both markers', () => {
		expect(unwrapProse('> > Nested quote line one\n> > continues here.')).toBe(
			'> > Nested quote line one continues here.'
		);
	});

	it('never joins a GitHub Alert marker into the line after it', () => {
		// `> [!WARNING]` only renders as the colored callout when its marker
		// sits alone on the blockquote's first line -- CommonMark itself sees
		// no reason not to join it into the next line (lazy continuation, no
		// blank line between them), which is exactly what broke this real
		// file's warning box during #776's own migration.
		const document_ =
			'> [!WARNING]\n> **Superseded.** Do not build from this document.\n>\n> More detail continues\n> onto a second line.';
		expect(unwrapProse(document_)).toBe(
			'> [!WARNING]\n> **Superseded.** Do not build from this document.\n>\n> More detail continues onto a second line.'
		);
	});

	it.each(['[!NOTE]', '[!TIP]', '[!IMPORTANT]', '[!CAUTION]'])(
		'recognizes %s as an alert marker too',
		(marker) => {
			const document_ = `> ${marker}\n> Body text continues\n> onto a second line.`;
			expect(unwrapProse(document_)).toBe(`> ${marker}\n> Body text continues onto a second line.`);
		}
	);

	it('joins an unordered list item wrapped across two lines', () => {
		const document_ =
			'- **Goal**: carry one Client for a Practice she does not belong to, see the money on\n  that job, and see nothing else of the Practice';
		expect(unwrapProse(document_)).toBe(
			'- **Goal**: carry one Client for a Practice she does not belong to, see the money on that job, and see nothing else of the Practice'
		);
	});

	it('joins an ordered list item wrapped across two lines', () => {
		expect(
			unwrapProse('1. First step of the process continues\n   onto the next line for clarity.')
		).toBe('1. First step of the process continues onto the next line for clarity.');
	});

	it('joins each paragraph of a loose list item, keeping the blank line between them', () => {
		const document_ =
			'- First paragraph of the item\n  continues here.\n\n  Second paragraph of the same item\n  continues too.\n\nAfter the list, a new top-level paragraph.';
		expect(unwrapProse(document_)).toBe(
			'- First paragraph of the item continues here.\n\n  Second paragraph of the same item continues too.\n\nAfter the list, a new top-level paragraph.'
		);
	});

	it('ends a list item at a dedented line that is not itself a list item', () => {
		const document_ =
			'- Item text continues\n  more item text.\nNot part of the item, dedented paragraph.';
		expect(unwrapProse(document_)).toBe(
			'- Item text continues more item text.\nNot part of the item, dedented paragraph.'
		);
	});

	it('recurses into a nested list, joining and re-indenting each nested item', () => {
		const document_ =
			'- Outer item text\n  - Inner item one\n  - Inner item two continues\n    onto next line.';
		expect(unwrapProse(document_)).toBe(
			'- Outer item text\n  - Inner item one\n  - Inner item two continues onto next line.'
		);
	});

	it('preserves a marker whose spacing to its text is wider than one space', () => {
		const document_ = '-   Item with wide spacing continues\n    onto the next line.';
		expect(unwrapProse(document_)).toBe('-   Item with wide spacing continues onto the next line.');
	});

	it('keeps a two-trailing-space hard break as its own line inside the paragraph', () => {
		const document_ =
			'Line one with a break  \nLine two after the break continues\nonto line three.';
		expect(unwrapProse(document_)).toBe(
			'Line one with a break  \nLine two after the break continues onto line three.'
		);
	});

	it('keeps a trailing-backslash hard break as its own line inside the paragraph', () => {
		const document_ =
			'First line ends with backslash\\\nSecond line finishes the thought\ncontinuing here.';
		expect(unwrapProse(document_)).toBe(
			'First line ends with backslash\\\nSecond line finishes the thought continuing here.'
		);
	});

	it('passes YAML front matter through untouched and still unwraps the body', () => {
		const document_ = '---\nname: Test\ncolor: blue\n---\n\nBody paragraph line one\ncontinues here.';
		expect(unwrapProse(document_)).toBe(
			'---\nname: Test\ncolor: blue\n---\n\nBody paragraph line one continues here.'
		);
	});

	it('falls back to ordinary body content when a leading --- never closes', () => {
		const document_ = '---\nname: Test\ncolor: blue\n\nBody paragraph line one\ncontinues here.';
		expect(unwrapProse(document_)).toBe(
			'---\nname: Test color: blue\n\nBody paragraph line one continues here.'
		);
	});

	it('preserves a trailing newline when the source has one, and adds none when it does not', () => {
		expect(unwrapProse('Simple line.\n')).toBe('Simple line.\n');
		expect(unwrapProse('Simple line.')).toBe('Simple line.');
		expect(unwrapProse('Line one\nline two')).toBe('Line one line two');
	});

	it('is idempotent: unwrapping an already-unwrapped document changes nothing further', () => {
		const document_ =
			'# Title\n\n- **Item**: some text\n\n> A quote\n\n| A | B |\n| --- | --- |\n| 1 | 2 |\n\nA closing paragraph.\n';
		const once = unwrapProse(document_);
		expect(unwrapProse(once)).toBe(once);
	});
});

const repoRoot = path.join(fileURLToPath(new URL('../../', import.meta.url)), '..');

// `docs/research/transcripts/` is verbatim auto-generated captions, the
// same exclusion `spelling.usage.spec.ts` makes and for the same reason:
// nobody hand-wrapped it, so nobody should hand-unwrap it either.
// `docs/design/doula-cloud.export.md` is generated by `bun run
// design:export` from `scripts/design-export.ts`'s own header template --
// fixed at that source, not by rewriting its output (see that script's
// `renderExport`); rewriting the committed file here without also fixing
// the generator would only be undone by the next export.
const documentFiles = globSync('docs/**/*.md', { cwd: repoRoot }).filter(
	(file) =>
		!file.startsWith('docs/research/transcripts/') && file !== 'docs/design/doula-cloud.export.md'
);

// CONTEXT.md and CLAUDE.md are prose read the same raw way an ADR is; both
// carry the sixth AC's "any other root-level markdown carrying prose".
// README.md is the third and only other root-level `.md` file.
const rootProseFiles = ['CONTEXT.md', 'README.md', 'CLAUDE.md'];

const proseFiles = [...documentFiles, ...rootProseFiles].toSorted((a, b) => a.localeCompare(b));

// Read and swept once, at module scope, rather than inside each `it.each`
// case -- the same reason `spelling.usage.spec.ts` and `layout.usage.
// spec.ts` do theirs (#1211, docs/testing.md's "whole-tree scan" note): a
// per-file read charged against each generated test's own 5s
// `testTimeout` is fine quiet, but a scan repeated this many times is the
// shape that timed out under the full suite's contention for disk and CPU
// and then passed again on a bare rerun of the same commit.
const sweep = proseFiles.map((file) => ({
	file,
	content: readFileSync(path.join(repoRoot, file), 'utf8')
}));

describe('every in-scope doc carries no hard-wrapped prose', () => {
	it('finds the docs tree at all, so an empty sweep cannot pass silently', () => {
		expect(documentFiles.length).toBeGreaterThan(100);
	});

	it.each(sweep)('$file has nothing unwrapProse would change', ({ file, content }) => {
		expect(
			unwrapProse(content),
			`${file} has a hard-wrapped paragraph, list item or blockquote -- run unwrapProse over it (see #776) and commit the result`
		).toBe(content);
	});
});
