/**
 * The mark has one source: docs/marketing/brand.md and the reference
 * drawings beside it in docs/marketing/brand/ (#1000, #1486).
 *
 * An SVG served as an icon is rendered outside the document, so it can
 * import nothing and each served copy is a real second file. This is the
 * one place that can see all of them -- app/, site/ and docs/ -- so it is
 * what keeps a copy from becoming a second drawing.
 */

import { describe, expect, test } from 'bun:test';
import { execFile } from 'node:child_process';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { promisify } from 'node:util';

const repoRoot = path.resolve(import.meta.dir, '..');
const BRAND_SHEET = 'docs/marketing/brand.md';
const BRAND_DRAWINGS = 'docs/marketing/brand/';

function read(file: string): Promise<string> {
  return readFile(path.join(repoRoot, file), 'utf8');
}

describe('the icon in a square slot', () => {
  // The browser tab of the app, the app's installed icon (the manifest's
  // `icons` entry), and the browser tab of the marketing site.
  const served = [
    'app/src/lib/assets/favicon.svg',
    'app/static/icon.svg',
    'site/static/favicon.svg',
  ];

  test.each(served)('%s is the plum tile, byte for byte', async (file) => {
    expect(await read(file)).toBe(await read(`${BRAND_DRAWINGS}icon.svg`));
  });
});

describe('the path data of the mark', () => {
  // The outer line and the inner arch, as the reference drawings write
  // them. A file that holds one of them holds a copy of the mark.
  const strokes = ['137.97-44 44 44 0 0 1 44.03 44', 'a32 32 0 0 1 64 0'];

  // The canvas is generated by the pen.dev app and is never hand-edited,
  // so it can carry no comment (CLAUDE.md, ADR-0019). It also does not
  // store the SVG path string in a form a comment could sit beside.
  const cannotCarryAComment = new Set(['docs/design/doula-cloud.pen']);

  async function filesThatHold(needle: string): Promise<string[]> {
    const { stdout } = await promisify(execFile)(
      'git',
      ['grep', '-l', '--untracked', '-F', needle],
      { cwd: repoRoot }
    );
    return stdout.split('\n').filter(Boolean);
  }

  test('is copied only into a file that names the brand sheet as its source', async () => {
    const holders = new Set(
      (await Promise.all(strokes.map(filesThatHold))).flat()
    );
    const copies = [...holders].filter(
      (file) =>
        !file.startsWith(BRAND_DRAWINGS) && !cannotCarryAComment.has(file)
    );

    // A sweep that finds nothing proves nothing.
    expect(copies.length).toBeGreaterThan(0);

    const unsourced: string[] = [];
    for (const file of copies) {
      if (!(await read(file)).includes(BRAND_SHEET)) unsourced.push(file);
    }
    expect(unsourced).toEqual([]);
  });
});
