#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Authored for #242: stand up the Stripe Sandbox every already-
# merged Stripe code path (#73, #77-#82) has been waiting on.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

# Values land in app/.env.local, which bun auto-loads for `bun run dev:full`
# and app/.gitignore already excludes. Nothing here belongs in git.
ENV_FILE="app/.env.local"

# Local addresses, from app/e2e/ports.ts. Stripe forwards straight to the
# Go BFF's own port, not through the vite dev proxy -- one hop fewer to go
# wrong on a signature check that needs the exact raw body.
readonly LOCAL_API="http://127.0.0.1:18080"
readonly LOCAL_APP="http://localhost:5173"

# The deployed BFF. Stripe posts to the raw Cloud Run URL rather than to
# https://doula-cloud-app.web.app/api/... : Firebase Hosting's /api/**
# rewrite is a proxy in front of a signature check over the exact request
# bytes, and there is no reason to put a CDN in that path.
readonly CLOUD_RUN_URL="https://doula-api-yrg7ybdc2q-uc.a.run.app"
readonly APP_ORIGIN="https://doula-cloud-app.web.app"
readonly GCP_PROJECT="doula-cloud"
readonly GCP_REGION="us-central1"

# $5.00, per #242's open decision. Stripe holds amounts in cents.
readonly CREDIT_UNIT_AMOUNT=500

[[ -f CLAUDE.md && -d api && -d app ]] || {
  printf 'Run this from the repo root: bash scripts/stripe-setup.sh\n' >&2
  exit 1
}

banner "Doula Cloud · Stripe Sandbox setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "A mailbox on doula.cloud to own the account"
say "Stripe sends disputes, payout notices and Connect alerts to the account"
say "owner's address. Root that in a company mailbox on doula.cloud, not in"
say "a personal address: the mailbox has to outlive whoever set it up."
say ""
say "Doula Cloud uses admin@doula.cloud, hosted on Squarespace email with a"
say "Gmail alias in front of it. Google Workspace works too, and costs about"
say "\$8.40/user/month. Either is fine. What matters is the domain."
say ""
note "admin@doula.cloud is already the Google Sign-In support address in"
note "firebase.json, so it is the address a Practice may already have seen."
say ""
note "Worth adding before launch, but not now: support@doula.cloud and"
note "billing@doula.cloud."
ask STRIPE_ACCOUNT_EMAIL "Which address will own the Stripe account?"
write_env STRIPE_ACCOUNT_EMAIL "$STRIPE_ACCOUNT_EMAIL"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the Stripe account"
say "A Sandbox is a full environment: the real API, real webhooks, fake card"
say "numbers, and no money movement. Nothing here needs a bank account."
say ""
open_url "https://dashboard.stripe.com/register"
step "Register with $STRIPE_ACCOUNT_EMAIL"
step "Business name: Doula Cloud. Country: United States."
step "Stripe will offer to 'activate payments' or 'complete your profile'."
note "  Skip it. Activation is live mode, and #242 rules live mode out."
say ""
step "One screen is a real fork: 'How do you want to manage tax, fraud, and"
note "  disputes?' Choose 'Pick what you need', NOT the recommended"
note "  'Let us handle it'."
note ""
note "  'Let us handle it' is Managed Payments, where Stripe becomes the"
note "  merchant of record: legally the seller, remitting VAT and sales tax"
note "  and absorbing chargebacks, for 3.5% on top of the card fee. That"
note "  suits a business that only sells its own product. Doula Cloud has a"
note "  second surface where the Practice is the merchant and we are the"
note "  platform (Connect, #78-#82), and every merged Stripe code path"
note "  assumes the platform posture: our own Price, our own Checkout"
note "  Session, our own Customer, our own webhook."
note ""
say ""
step "The next screen pre-ticks three products. Leave only one ticked."
note ""
note "  Create subscriptions -> UNTICK. #45 settled that there is no"
note "  subscription and no tiers: a Practice prepays per Engagement from a"
note "  credit ledger, and the purchase is a one-time Checkout Session in"
note "  mode=payment. Nothing here creates a Stripe Subscription."
note ""
note "  Send invoices -> KEEP. That is surface B: collection_method="
note "  send_invoice, days_until_due=30. Those invoices are raised on the"
note "  connected account rather than on ours, so this may not strictly be"
note "  needed -- but it is free to leave on and a surprise to leave off."
note ""
note "  Collect tax -> UNTICK. Stripe Tax is usage-priced and wants an"
note "  origin address and a tax code per Price before it does anything."
note "  SaaS sales tax is a launch question. Switching it on later is one"
note "  click; switching it on now stands between you and a Checkout page."
say ""
warn "Do NOT click 'Connect to a platform instead' on that screen."
note "  It means the opposite of how it reads: it makes THIS account a"
note "  connected account under someone else's platform, which is the role"
note "  a Practice plays, not the role we play. Connect is enabled on its"
note "  own page, at stage 6."
say ""
step "'Choose how to set up Stripe' -> Set up in the Dashboard."
note "  The only low-stakes fork in this stage: it picks an onboarding path,"
note "  not an account setting. The integration is already written, so the"
note "  AI-tool path would be guidance for work that is done."
step "The last screen offers 'Get your live account now' and 'Go to"
note "  sandbox'. Go to sandbox."
say ""
note "  Stripe renamed test mode, and CONTEXT.md follows the new name. A"
note "  SANDBOX is a separate environment with its own data and"
note "  its own API keys. Keys from it still start sk_test_, so nothing the"
note "  code expects changes -- but a sandbox is an environment, not a"
note "  toggle, and that matters at stage 4."
say ""
warn "Every key you copy from here on must start sk_test_ or whsec_."
pause "Account created?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Install and log in to the Stripe CLI"
say "The CLI does two jobs: it creates the Product, Price and webhook"
say "endpoints for you, and it forwards live test events to your laptop."
say ""
if command -v stripe >/dev/null 2>&1; then
  note "stripe is already installed: $(stripe --version 2>&1 | head -n1)"
else
  say "Installing it now..."
  if command -v brew >/dev/null 2>&1; then
    brew install stripe/stripe-cli/stripe
  else
    warn "Homebrew not found. Install the CLI by hand, then re-run:"
    note "  https://docs.stripe.com/stripe-cli"
    exit 1
  fi
fi
say ""
step "A browser tab opens with a pairing code. Check the code matches, then"
note "  press Allow access."
pause "Press Enter to run 'stripe login'"
stripe login
say ""
stripe config --list | grep -E 'account_id|display_name' || true
confirm "Is that the Doula Cloud account?" || {
  warn "Run 'stripe login' again against the right account, then re-run this wizard."
  exit 1
}

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "The platform secret key"
say "One key serves both Stripe surfaces: the Practice paying us for credits,"
say "and the Practice's own Clients paying the Practice through Connect."
say "api/main.go reads it once and hands it to both clients."
say ""
open_url "https://dashboard.stripe.com/test/apikeys"
warn "Check the environment switcher first."
note "  A sandbox has its own keys. If the switcher does not say you are in"
note "  the Doula Cloud sandbox, switch to it and re-open API keys -- a key"
note "  copied from the wrong environment fails later as a signature or"
note "  'no such price' error, which reads like a code bug and is not one."
say ""
step "Find the row 'Secret key'. Press Reveal test key."
step "Copy the whole value. It starts sk_test_"
say ""
warn "This is a credential. It is hidden as you paste it, and it is written"
warn "to app/.env.local, which git ignores. Never paste it into an issue."
ask_secret STRIPE_API_KEY "Paste the secret key:"
case "$STRIPE_API_KEY" in
  sk_test_*) : ;;
  sk_live_*) warn "That is a LIVE key. #242 is Sandbox only."; exit 1 ;;
  *)         warn "That does not look like a Stripe secret key."; exit 1 ;;
esac
write_env STRIPE_API_KEY "$STRIPE_API_KEY"

# Every Stripe object below is created over the REST API with curl rather
# than through the dashboard: it is repeatable, it records exactly what was
# made, and it keeps the human's part of this wizard to the things only a
# human can do.
stripe_post() {
  local path="$1"; shift
  curl -sS -X POST "https://api.stripe.com/v1/$path" -u "$STRIPE_API_KEY:" "$@"
}
# json_field FIELD reads one top-level field out of a Stripe response on
# stdin, and fails loudly on a Stripe error object rather than returning an
# empty string that the next call would then send as an id.
json_field() {
  python3 -c '
import json, sys
body = json.load(sys.stdin)
if "error" in body:
    sys.stderr.write("Stripe refused: " + body["error"].get("message", "") + "\n")
    raise SystemExit(1)
print(body[sys.argv[1]])
' "$1"
}

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "The credit Product and Price"
say "A Price is a fixed amount. Checkout multiplies it by the quantity the"
say "Practice buys, so one Price covers every purchase size (#45: no packs)."
say ""
note "One credit = one Engagement = one birth. First 3 per Practice are free."
note "Pilot amount: \$$((CREDIT_UNIT_AMOUNT / 100)).$(printf '%02d' $((CREDIT_UNIT_AMOUNT % 100))) per credit."
say ""
STRIPE_CREDIT_PRICE_ID=$(_existing STRIPE_CREDIT_PRICE_ID || true)
create_price=yes
if [[ -n "$STRIPE_CREDIT_PRICE_ID" ]]; then
  note "A Price is already recorded: $STRIPE_CREDIT_PRICE_ID"
  confirm "Create a second one anyway?" || create_price=no
fi
if [[ "$create_price" == yes ]]; then
  say "Creating the Product..."
  product_id=$(stripe_post products \
    -d "name=Engagement credit" \
    -d "description=One Doula Cloud Engagement. Consumed when a Practice creates an Engagement." \
    | json_field id)
  say "  product: $product_id"
  say "Creating the Price..."
  STRIPE_CREDIT_PRICE_ID=$(stripe_post prices \
    -d "product=$product_id" \
    -d "unit_amount=$CREDIT_UNIT_AMOUNT" \
    -d "currency=usd" \
    | json_field id)
  write_env STRIPE_CREDIT_PRICE_ID "$STRIPE_CREDIT_PRICE_ID"
fi

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Enable Connect, with Standard accounts"
say "Connect is the second surface: a Client pays a Practice directly, and"
say "the money never touches us. api/internal/payments creates a Standard"
say "account per Practice and onboards it through a hosted Stripe page."
say ""
open_url "https://dashboard.stripe.com/test/connect/accounts/overview"
step "Press Get started, and fill in the platform profile Stripe asks for."
step "Where it asks what your platform does, the honest answer is: software"
note "  for doula practices; the practices invoice their own clients."
step "Where it asks who your users are, choose businesses in the US."
say ""
note "You do not choose Standard in the dashboard. The account type is set"
note "per account at creation time, and payments/stripe_api_client.go:32"
note "already passes type=standard. Connect only has to be switched on."
say ""
pause "Press Enter once the Connect overview page stops asking you to set up"
say ""
say "Checking that Connect really is enabled, by creating a throwaway"
say "account and deleting it again..."
probe_account=$(stripe_post accounts -d "type=standard" | json_field id) || {
  warn "Connect is not enabled yet. Finish the platform profile and re-run."
  exit 1
}
curl -sS -X DELETE "https://api.stripe.com/v1/accounts/$probe_account" \
  -u "$STRIPE_API_KEY:" >/dev/null
say "  Connect is enabled. Probe account $probe_account created and deleted."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Local webhook forwarding"
say "Stripe cannot reach your laptop. 'stripe listen' opens an outbound"
say "connection to Stripe and replays every test event to a local URL."
say ""
say "Reading the forwarding signing secret..."
LOCAL_WHSEC=$(stripe listen --print-secret)
say "  $LOCAL_WHSEC"
say ""
warn "One session, one secret, two endpoints."
note "The BFF reads two separate secrets, and in production they ARE two"
note "different values (stage 8 creates two endpoints). But a single"
note "'stripe listen' session signs everything it forwards with its own one"
note "secret, whether it goes to --forward-to or --forward-connect-to. So"
note "both local variables get the same value. That is correct, not a slip."
write_env STRIPE_WEBHOOK_SECRET "$LOCAL_WHSEC"
write_env STRIPE_CONNECT_WEBHOOK_SECRET "$LOCAL_WHSEC"
say ""
say "From now on, a local walk needs three terminals:"
step "1. bun run dev:full          (from app/)"
step "2. the forwarder, below"
step "3. this wizard"
say ""
note "The forwarder command, saved to scripts/stripe-listen.sh:"
cat > scripts/stripe-listen.sh <<LISTEN
#!/usr/bin/env bash
# Forwards Stripe test events to the local BFF (see docs/environment.md).
# Both destinations are signed with this session's one secret, which is
# what STRIPE_WEBHOOK_SECRET and STRIPE_CONNECT_WEBHOOK_SECRET both hold
# in app/.env.local. Run it beside \`bun run dev:full\`.
exec stripe listen \\
  --forward-to $LOCAL_API/api/stripe/webhook \\
  --forward-connect-to $LOCAL_API/api/stripe/connect-webhook
LISTEN
chmod +x scripts/stripe-listen.sh
say "  bash scripts/stripe-listen.sh"
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "The two deployed webhook endpoints"
say "The deployed BFF is reachable from the internet, so Stripe posts to it"
say "directly. Each endpoint gets its own signing secret, returned once, at"
say "creation, and never shown again by the API."
say ""
warn "A secret returned once is a secret that can be lost. Each one below is"
warn "written to $ENV_FILE the instant it arrives, so a failure in a later"
warn "stage cannot strand you with two endpoints you can no longer sign for."
say ""
DEPLOYED_WHSEC=$(_existing DEPLOYED_STRIPE_WEBHOOK_SECRET || true)
DEPLOYED_CONNECT_WHSEC=$(_existing DEPLOYED_STRIPE_CONNECT_WEBHOOK_SECRET || true)
create_endpoints=yes
if [[ -n "$DEPLOYED_WHSEC" && -n "$DEPLOYED_CONNECT_WHSEC" ]]; then
  note "Both endpoints were already created by an earlier run, and both"
  note "secrets are still in $ENV_FILE. Creating them again would leave"
  note "duplicate endpoints delivering every event twice."
  confirm "Create a second pair anyway?" || create_endpoints=no
fi
if [[ "$create_endpoints" == yes ]]; then
  say "Platform endpoint (a Practice buying credits)..."
  DEPLOYED_WHSEC=$(stripe_post webhook_endpoints \
    -d "url=$CLOUD_RUN_URL/api/stripe/webhook" \
    -d "enabled_events[]=checkout.session.completed" \
    -d "description=Doula Cloud platform billing (credits) - Sandbox" \
    | json_field secret)
  write_env DEPLOYED_STRIPE_WEBHOOK_SECRET "$DEPLOYED_WHSEC"
  say ""
  say "Connect endpoint (a Practice's own account and invoices)..."
  say "  connect=true is what makes it receive events from connected accounts"
  say "  rather than from ours."
  DEPLOYED_CONNECT_WHSEC=$(stripe_post webhook_endpoints \
    -d "url=$CLOUD_RUN_URL/api/stripe/connect-webhook" \
    -d "connect=true" \
    -d "enabled_events[]=account.updated" \
    -d "enabled_events[]=invoice.paid" \
    -d "enabled_events[]=invoice.payment_failed" \
    -d "description=Doula Cloud Connect (client payments) - Sandbox" \
    | json_field secret)
  write_env DEPLOYED_STRIPE_CONNECT_WEBHOOK_SECRET "$DEPLOYED_CONNECT_WHSEC"
fi
say ""
open_url "https://dashboard.stripe.com/test/workbench/webhooks"
note "Both endpoints should be listed there now."
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Store the deployed credentials in Secret Manager"
say "The deployed service reads its three credentials from Google Secret"
say "Manager, the same way it already reads DATABASE_URL. Nothing secret"
say "goes into ci.yml, and nothing secret goes into a Cloud Run env var."
say ""
# A gcloud session can expire during a wizard this long. Fail here, where
# nothing is half-done, rather than three commands in.
if ! gcloud auth print-access-token >/dev/null 2>&1; then
  warn "gcloud is not authenticated. In another terminal, run:"
  note "  gcloud auth login"
  pause "Press Enter once that is done"
  gcloud auth print-access-token >/dev/null || {
    warn "Still not authenticated. Nothing is lost: both deployed secrets are"
    warn "already in $ENV_FILE. Fix gcloud and re-run this wizard."
    exit 1
  }
fi

put_secret() {
  local name="$1" value="$2"
  if gcloud secrets describe "$name" --project "$GCP_PROJECT" >/dev/null 2>&1; then
    printf '%s' "$value" | gcloud secrets versions add "$name" \
      --project "$GCP_PROJECT" --data-file=- >/dev/null
    say "  $name: new version added"
  else
    printf '%s' "$value" | gcloud secrets create "$name" \
      --project "$GCP_PROJECT" --replication-policy=automatic --data-file=- >/dev/null
    say "  $name: created"
  fi
}
put_secret doula-cloud-stripe-api-key "$STRIPE_API_KEY"
put_secret doula-cloud-stripe-webhook-secret "$DEPLOYED_WHSEC"
put_secret doula-cloud-stripe-connect-webhook-secret "$DEPLOYED_CONNECT_WHSEC"
say ""
say "Granting the Cloud Run runtime account read access..."
RUNTIME_SA=$(gcloud run services describe doula-api \
  --region "$GCP_REGION" --project "$GCP_PROJECT" \
  --format='value(spec.template.spec.serviceAccountName)')
if [[ -z "$RUNTIME_SA" ]]; then
  project_number=$(gcloud projects describe "$GCP_PROJECT" --format='value(projectNumber)')
  RUNTIME_SA="${project_number}-compute@developer.gserviceaccount.com"
  note "  service uses the default compute account: $RUNTIME_SA"
fi
for s in doula-cloud-stripe-api-key doula-cloud-stripe-webhook-secret doula-cloud-stripe-connect-webhook-secret; do
  gcloud secrets add-iam-policy-binding "$s" \
    --project "$GCP_PROJECT" \
    --member "serviceAccount:$RUNTIME_SA" \
    --role roles/secretmanager.secretAccessor >/dev/null
  say "  $s: readable by the service"
done

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Point the deployed service at all of it"
say "Two plain env vars and three secret references. APP_BASE_URL and the"
say "Price id are not credentials, so they stay readable env vars."
say ""
gcloud run services update doula-api \
  --region "$GCP_REGION" --project "$GCP_PROJECT" \
  --update-env-vars "APP_BASE_URL=$APP_ORIGIN,STRIPE_CREDIT_PRICE_ID=$STRIPE_CREDIT_PRICE_ID" \
  --update-secrets "STRIPE_API_KEY=doula-cloud-stripe-api-key:latest,STRIPE_WEBHOOK_SECRET=doula-cloud-stripe-webhook-secret:latest,STRIPE_CONNECT_WEBHOOK_SECRET=doula-cloud-stripe-connect-webhook-secret:latest" \
  --quiet
say ""
say "Confirming the revision came up..."
curl -fsS "$CLOUD_RUN_URL/api/hello" && say ""
note "--update-env-vars and --update-secrets both merge, so DATABASE_URL and"
note "EXPECTED_ORIGINS are untouched. ci.yml deploys the same way"
note "(env_vars_update_strategy: merge), so a later push cannot wipe these."
pause

# psql runs one statement against the local stack's Postgres, the same way
# app/e2e/stack.ts does. Used below to read the row a webhook wrote,
# because the point of both walks is that the webhook is what wrote it.
psql_local() {
  (cd app && "${CONTAINER_ENGINE:-podman}" compose -f compose.e2e.yaml exec -T db \
    psql -U app -d app -c "$1")
}

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Walk A · Buy credits, end to end"
say "This is the step that has never once run. With no key it answered a"
say "bare 'internal error' (#233, #242). Now it should reach Checkout."
say ""
say "In two other terminals:"
step "cd app && bun run dev:full"
step "bash scripts/stripe-listen.sh"
say ""
pause "Both running?"
open_url "$LOCAL_APP"
step "Sign up as a new Practice, or sign in to one you already made."
step "Go to Billing. It reads 'Credit balance: 3'."
step "Set Quantity to 2 and press Buy credits."
step "Stripe's hosted Checkout page opens. Card: 4242 4242 4242 4242"
note "  Expiry: any future date. CVC: any 3 digits. ZIP: any 5 digits."
step "Pay. You land back on Billing with ?checkout=success in the URL."
say ""
warn "The redirect does NOT add the credits. The webhook does."
note "Watch terminal 2: 'checkout.session.completed --> 200'. The ledger is"
note "credited only by billing/webhook.go, never by the redirect (#45)."
say ""
pause "Press Enter to read the ledger"
psql_local "SELECT practice_id, origin, quantity, created_at FROM credit_ledger ORDER BY created_at DESC LIMIT 5;"
say ""
confirm "Is there a 'purchase' row with your quantity on it?" || {
  warn "Stop here and read terminal 2. A non-200 there is the whole story."
  exit 1
}

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Walk B · Connect onboarding, then an Invoice paid"
say "The other surface. The Practice onboards its own Stripe account, then"
say "raises an Invoice against a Contract and the Client pays it."
say ""
step "Go to Settings -> Payments. It reads 'Stripe Connect status: Not connected'."
step "Press Connect Stripe. Stripe's hosted onboarding opens."
say ""
note "Sandbox onboarding takes fake data, and Stripe offers to fill it in:"
note "  look for the 'Use test data' or 'Skip this form' link at the top."
note "If you fill it by hand:"
note "  Phone 000 000 0000, and the SMS code is 000000"
note "  Date of birth 01/01/1901   SSN last 4: 0000   Full SSN 000-00-0000"
note "  Address line 1: address_full_match"
note "  Bank routing 110000000, account 000123456789"
say ""
step "Finish. You land back on Settings -> Payments with ?connect=return."
say ""
warn "The three flags come from the account.updated webhook, not a poll."
pause "Press Enter to read the Practice's Connect columns"
psql_local "SELECT name, stripe_connect_account_id, stripe_connect_charges_enabled, stripe_connect_payouts_enabled, stripe_connect_details_submitted FROM practices;"
say ""
confirm "Is charges_enabled true?" || {
  warn "Check terminal 2 for 'account.updated'. Onboarding can also stay"
  warn "pending: re-open the Account Link and finish the outstanding item."
  exit 1
}
say ""
say "Now the Invoice."
step "Open a Client, then their Engagement, then the Contract section."
step "The Contract must be signed before an Invoice can be raised."
step "Enter an amount (say 1800) and press Create Invoice."
step "Stripe emails the hosted invoice. In a Sandbox nothing really sends,"
note "  so open it from the dashboard instead:"
open_url "https://dashboard.stripe.com/test/connect/accounts/overview"
step "Open the connected account, find the Invoice, open its payment page,"
note "  and pay it with 4242 4242 4242 4242."
say ""
pause "Press Enter to read the payments table"
psql_local "SELECT invoice_id, amount_cents, paid_at FROM payments ORDER BY paid_at DESC LIMIT 5;"
say ""
confirm "Is there a payments row?" || warn "Check terminal 2 for 'invoice.paid'."

finish
note "Next: docs/environment.md records every variable and where it lives."
note "Tell the agent the walks passed, so it can re-mark docs/test-plans/."
