// `bun run sync-icons` -- pulls the SVG assets for every icon in
// src/lib/components/atoms/Icon/manifest.ts from phosphor-icons/core and
// writes one generated module per icon into
// src/lib/components/atoms/Icon/generated, self-hosted (issue #96's
// delivery decision) rather than fetched at runtime or via an npm package.
// Both `duotone` and `light` weights are pulled per icon -- Icon.svelte
// auto-selects between them by render size.
//
// #96's decision text cites phosphor-icons/core's `raw/` folder as the
// source, but that folder holds Phosphor's editing sources (helper
// `<rect>`s, `<polyline stroke>` outlines, no single fill layer) --  not
// consumable icons. The upstream README documents `assets/` as the actual
// per-weight, ready-to-use export path, which is what this script uses;
// see the correction posted on #96.
import { mkdir, writeFile } from 'node:fs/promises';
import { iconManifest } from '../src/lib/components/atoms/Icon/manifest.ts';

const weights = ['duotone', 'light'] as const;
const sourceRoot = 'https://raw.githubusercontent.com/phosphor-icons/core/main/assets';
const targetDirectory = new URL('../src/lib/components/atoms/Icon/generated/', import.meta.url);

// Phosphor's duotone assets ship the secondary layer as a `<path>` carrying
// an `opacity="0.2"` attribute and the primary layer as a plain `<path>`
// (`light` assets are always a single plain `<path>`) -- that attribute is
// the only signal distinguishing the two, per #96's decision. Tag each path
// with the `icon-fg`/`icon-bg` class Icon.svelte's CSS targets, once here,
// so the component itself never has to re-derive it from raw markup.
function tagLayerClasses(svg: string): string {
	const inner = svg.replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');
	return inner.replaceAll(/<path\b([^>]*)\/>/g, (_match, attributes: string) => {
		const layerClass = attributes.includes('opacity=') ? 'icon-bg' : 'icon-fg';
		return `<path class="${layerClass}"${attributes}/>`;
	});
}

async function fetchLayerMarkup(name: string, weight: (typeof weights)[number]): Promise<string> {
	const url = `${sourceRoot}/${weight}/${name}-${weight}.svg`;
	const response = await fetch(url);
	if (!response.ok) {
		throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
	}

	return tagLayerClasses(await response.text());
}

await mkdir(targetDirectory, { recursive: true });

for (const name of iconManifest) {
	const [duotone, light] = await Promise.all(weights.map((weight) => fetchLayerMarkup(name, weight)));

	const generatedModule = `// Generated by \`bun run sync-icons\` from phosphor-icons/core. Do not edit by hand.
export const duotone = ${JSON.stringify(duotone)};
export const light = ${JSON.stringify(light)};
`;
	await writeFile(new URL(`${name}.ts`, targetDirectory), generatedModule);
	console.log(`synced ${name}.ts`);
}
