name: Deploy Hugo site to Firebase Hosting on merge
on:
  push:
    branches:
      - trunk
    paths:
      - "hugo/**"
      - "firebase.json"

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:trunk
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install dependencies
        run: bun install

      - name: Build Hugo site
        run: bun run build

      - name: Upload Hugo build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: hugo-public
          path: hugo/public
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Download Hugo build artifacts
        uses: actions/download-artifact@v8
        with:
          name: hugo-public
          path: hugo/public

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: doula-cloud
          workload_identity_provider: projects/850855848778/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: github-action-733741680@doula-cloud.iam.gserviceaccount.com

      - uses: oven-sh/setup-bun@v2

      - name: Deploy to Firebase
        run: bunx firebase-tools deploy --only hosting:hugo --non-interactive
